### PR TITLE
Increase coverage of natural gradient

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Increase the coverage of natural gradient.

### Details and comments

- Remove the pass of `auto_search==False`, which cannot be invoked by users.
- Set `self._qfi_method` with `QFI` so that `self.qfi_method` returns `CircuitQFI`.
- Try all combinations of grad_method, qfi_method, regularization. 
- Add some unit tests of natural gradients.

### CODE REVIEW

**Comment by t-imamichi** [comment]
I found that some combinations of grad_method and qfi_method do not pass the unit test. Could you take a look at it? @Zoufalc @BryceFuller

E.g.,
```
======================================================================
FAIL: test_natural_gradient_10___lin_comb____overlap_block_diag____perturb_diag_elements__ (test.aqua.operators.test_gradients.TestGradients)
Test the natural gradient
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ima/envs/qopt/lib/python3.7/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ima/tasks/0_2020/qiskit/aqua/test/aqua/operators/test_gradients.py", line 398, in test_natural_gradient
    decimal=0)
  File "/Users/ima/envs/qopt/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1044, in assert_array_almost_equal
    precision=decimal)
  File "/Users/ima/envs/qopt/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 0 decimals

Mismatched elements: 1 / 2 (50%)
Max absolute difference: 3.13933993
Max relative difference: 0.74746189
 x: array([-1.e+00,  1.e-07])
 y: array([-4.,  0.])
```

**Comment by Zoufalc** [comment]
Thanks for extending the coverage.
This is bc
1. the block-diagonal / diagonal argument only result in approximations. Thus, the result can deviate.
2. different regularization methods cannot always result in the same gradient values.

As an alternative I would suggest that we do not check equivalence with a value but check that the execution does not break.

**Comment by t-imamichi** [comment]
I see. Then, we have to pick up some relevant combinations. Do you have any suggestions?

**Comment by Zoufalc** [comment]
What we could do is to check that 'lin_comb', 'param_shift' and 'fin_diff' all give approx. the same results for the different combinations of regularizers and qfi types.

**Comment by t-imamichi** [comment]
Thank you. I change it to pass the unit test. It seems fine now.

**Comment by t-imamichi** [comment]
There are still two missing coverage as follows. I leave them now because we need to find out parameter values to go through these passes.
@Zoufalc I think you added these codes because you needed them in some situations. If so, could you add them to unit tests?
image
image

**Review by Zoufalc — APPROVED** [review]

**Pull request merged**
